name: Push DNS Changes

on:
  push:
    branches:
      - 'main'
    paths:
      - 'dnsconfig.js'
      - 'creds.json'
      - 'domains/*.js'
  schedule:
     - cron: "15 1 * * *"
       timezone: "America/Anchorage"

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ !cancelled() }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v7

      - name: DNSControl Push
        uses: DNSControl/dnscontrol-action@6c99137eebf667295447b7fd2ec443e51b53a48e
        with:
          check: true
          cmdargs: push
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

